title: BLumia's Darkness World
subtitle: Hey! Wrapzone somewhere? Anyone here?
email: your-email@example.com
footer-text: <a href="https://github.com/BLumia/jekyll-theme-mutter">Mutter</a> theme build with <i class="i i-heart"></i> on <i class="i i-octodex"></i>
footer-copyright: BLumia &copy; 2018
description: >- # this means to ignore newlines until "header_pages:"
  BLumia's Personal Homepage

header_pages:
  - index.md
  - posts.md
  - Creative.md
  - about.md

defaults: # leave some default front-matter for posts
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"


# Build settings
markdown: kramdown
theme: jekyll-theme-mutter
plugins:
  - jekyll-feed
  - jekyll-seo-tag

